name: DOCS

on:
  schedule:
    - cron: 0 0 * * 6
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  generate-and-deploy:
    name: DOCS
    concurrency:
      group: make-docs-website
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      # https://github.com/japgolly/setup-everything-scala
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y texlive-xetex pandoc pandoc-citeproc

      - name: Make Site
        run: |
          mkdir site
          echo "theme: jekyll-theme-cayman" > site/_config.yml
          cat <<EOF > site/README.md
            ---
            layout: post
            title: Title of the page
            ---
            
            # Documentation website

            ## Article about something
            [Article](./article.pdf).
            
            ## The Protocol

            You can find the [Protocol here](./protocol.pdf).
          EOF

      - name: Generate Protocol
        run: |
          ./docs/protocol/make.sh 
          cp ./docs/protocol/protocol.docx site
          cp ./docs/protocol/protocol.pdf site

      - name: Generate Article
        run: |
          make -C ./docs/article/
          cp ./docs/article/article.pdf site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site # The folder the action should deploy.
